language: go
go_import_path: github.com/fhs/go-netcdf
dist: bionic

env:
  global:
    - GO111MODULE=on

go:
  - "1.14.x"
  - "1.15.x"

install: ignore

script:
  - test `gofmt -l . | wc -l` = 0
  - |
    docker run --rm \
      -v "$(go env GOROOT):/usr/local/go" \
      -v "$(pwd):/go/src/github.com/fhs/go-netcdf" -w "/go/src/github.com/fhs/go-netcdf" \
      golang:buster \
      bash -c "
        apt-get update &&
        apt-get install -y libnetcdf-dev &&
        go version &&
        go test -v -race -coverprofile=coverage.txt -covermode=atomic ./..."

after_success:
  - bash <(curl -s https://codecov.io/bash)
